export const products = [
  {
    id: "p01",
    name: "Product A",
    price: 50,
    created: new Date("2021/08/1"),
    categories: ["food"],
    weight: 1.4,
    available: true,
  },
  {
    id: "p02",
    name: "Product B",
    price: 150,
    created: new Date("2021/08/1"),
    categories: ["device", "communication"],
    weight: 0.3,
    available: false,
  },
  {
    id: "p03",
    name: "Product C",
    price: 30,
    created: new Date("2021/08/3"),
    categories: ["device", "toys"],
    weight: 5,
    available: false,
  },
  {
    id: "p04",
    name: "Product D",
    price: 250,
    created: new Date("2021/08/2"),
    categories: ["shelter", "farming"],
    weight: 3.5,
    available: true,
  },
  {
    id: "p05",
    name: "Product E",
    price: 40,
    created: new Date("2021/09/1"),
    categories: ["food"],
    weight: 1,
    available: true,
  },
  {
    id: "p06",
    name: "Product F",
    price: 50,
    created: new Date("2021/08/1"),
    categories: ["food"],
    weight: 2,
    available: false,
  },
];
